name: CI (conda)
on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: ['windows-latest']
        python-version: [3.7.4]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2 # checkout action to checkout code
      - name: Setup Miniconda
        uses: goanpeca/setup-miniconda@v1 # action referencing someone else's repo's action
        with:
          auto-update-conda: true
          auto-activate-base: false
          miniconda-version: 'latest'
          python-version: ${{ matrix.python-version }}
          environment-file: githubActionsEnv.yml
          activate-environment: githubActionsEnv
      - name: Conda list
        shell: pwsh
        run: conda list
      - name: Test with pytest
        shell: pwsh
        run: |
          if("${{ matrix.os }}" -eq "windows-latest"){
             pytest tests
          } else {
             pytest --cov=./ --cov-report=xml
          }
      # - name: Make Docker image
      #   # referencing directory that contains the action
      #   uses: ./.github/actions/docker-action
  push_docker_to_registry:
    name: Push image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          # See Github secrets: https://docs.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets
          username: ${{ secrets.MJ_DOCKER_USERNAME }}
          password: ${{ secrets.MJ_DOCKER_PASSWORD }}
          repository: mjtung/docker-registry-test
          tag_with_ref: true

